import { defineConfig } from 'vite'
import tailwindcss from '@tailwindcss/vite';
import laravel from 'laravel-vite-plugin'
import { wordpressPlugin, wordpressThemeJson } from '@roots/vite-plugin';

export default defineConfig({
  base: '/home2/stunnws2w/laravel.stunninghub.in',
  plugins: [
    tailwindcss(),
    laravel({
      input: [
        'resources/css/app.css',
        'resources/js/app.js',
        'resources/css/bootstrap.min.css',
        'resources/css/owl.carousel.min.css',
        'resources/css/slicknav.css',
        'resources/css/flaticon.css',
        'resources/css/gijgo.css',
        'resources/css/animate.min.css',
        'resources/css/animated-headline.css',
        'resources/css/magnific-popup.css',
        'resources/css/fontawesome-all.min.css',
        'resources/css/themify-icons.css',
        'resources/css/slick.css',
        'resources/css/nice-select.css',
        'resources/css/style.css',
        'resources/css/editor.css',
        'resources/js/editor.js',
        'resources/images/gallery/cat1.png',
        'resources/images/gallery/cat2.png',
        'resources/images/gallery/team1.png',
        'resources/images/gallery/team2.png',
        'resources/images/gallery/team3.png',
        'resources/images/gallery/gallery1.png',
        'resources/images/gallery/gallery2.png',
        'resources/images/gallery/gallery3.png',
        'resources/images/gallery/gallery4.png',
        'resources/images/gallery/gallery5.png',
        'resources/images/gallery/gallery6.png',
        'resources/images/icon/price.svg',
        'resources/images/icon/check.svg',
        'resources/images/gallery/about.png',
        'resources/images/gallery/blog1.png',
        'resources/images/gallery/blog2.png',
        'resources/images/gallery/video-bg.png',
        'resources/images/icon/icon1.svg',
        'resources/images/icon/icon2.svg',
        'resources/images/icon/icon3.svg',
        'resources/images/hero/h1_hero.png',
        'resources/images/blog/learn_about_bg.png',
        'resources/js/vendor/modernizr-3.5.0.min.js',
        'resources/js/vendor/jquery-1.12.4.min.js',
        'resources/js/popper.min.js',
        'resources/js/bootstrap.min.js',
        'resources/js/jquery.slicknav.min.js',
        'resources/js/owl.carousel.min.js',
        'resources/js/slick.min.js',
        'resources/js/wow.min.js',
        'resources/js/animated.headline.js',
        'resources/js/jquery.magnific-popup.js',
        'resources/js/gijgo.min.js',
        'resources/js/jquery.nice-select.min.js',
        'resources/js/jquery.sticky.js',
        'resources/js/jquery.counterup.min.js',
        'resources/js/waypoints.min.js',
        'resources/js/jquery.countdown.min.js',
        'resources/js/hover-direction-snake.min.js',
        'resources/js/contact.js',
        'resources/js/jquery.form.js',
        'resources/js/jquery.validate.min.js',
        'resources/js/mail-script.js',
        'resources/js/jquery.ajaxchimp.min.js',
        'resources/js/plugins.js',
        'resources/js/main.js',
      ],
      refresh: true,
    }),

    wordpressPlugin(),

    // Generate the theme.json file in the public/build/assets directory
    // based on the Tailwind config and the theme.json file from base theme folder
    wordpressThemeJson({
      disableTailwindColors: false,
      disableTailwindFonts: false,
      disableTailwindFontSizes: false,
    }),
  ],
  resolve: {
    alias: {
      '@scripts': '/resources/js',
      '@styles': '/resources/css',
      '@fonts': '/resources/fonts',
      '@images': '/resources/images',
    },
  },
})
